# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "f2MZSAFEOhupW7DlxyFqfdtKRt94q7toFxHVIMRYPBjbXqN5LLZJELVNHaTorm9hyVMVOUueJaDAzXjVmTtBQF3v4qiyThMZN/Nb9OxvkgtcWRAwfgLmfsGZMM7jt7C7xGuDjL4QMeSMrpUIbJI9WcCavib4b0/HN3Wf6a6YNc2cLUG0bYAi4W9HUixbB70zj4sBtNdVVa7asmEXdYeRnfVQua3Y2s2+H166eW+O6Cl6gfQsgIkeQHqYRZpLirxj+EP48YJDzTZcI17roygCYNXU3dQBoE1FcAz39QMozzkTzZ0OSyD7+3AmzfkrjeHRG1nxJ3j7HQFwYrwicfj5/pznxWGpG6TNly33Tgu0CNTcKCrzXzN/nUFbPeahID+gKzwTkFDvv3vmelFTlOtp+OA1y7EloMTV++fIYObOmD8rBk/qOBqOcDuj9hsrjt46FHkJekSB4TPvsqwgkSl8cPgHwsHUsTE6EXJZ+IM72aM5npDdoU+lj7jECrO2mEwDsiZptqmSqho1U5dQLUxN2xKPd3X0NYFVazUl+YSwaXh/bPWOmsfamDbvrEh3Z2Tb+QGCGvXWuVMyXJd7/clU92eKOYEKB32WKUGeYOSVo0762ItzILC5QgN9iL42wPEJpS2Nat6OcbE8/GiMvQKklZ7nxCXMzxs07YTFuziDf0Y="

matrix:
  include:
    - env: CONFIG=osx_mpimpich UPLOAD_PACKAGES=True PLATFORM=osx-64
      os: osx
      osx_image: xcode9.4

    - env: CONFIG=osx_mpinompi UPLOAD_PACKAGES=True PLATFORM=osx-64
      os: osx
      osx_image: xcode9.4

    - env: CONFIG=osx_mpiopenmpi UPLOAD_PACKAGES=True PLATFORM=osx-64
      os: osx
      osx_image: xcode9.4

script:
  - export CI=travis
  - export GIT_BRANCH="$TRAVIS_BRANCH"

  - if [[ ${PLATFORM} =~ .*osx.* ]]; then ./.travis/run_osx_build.sh; fi
